openapi: 3.0.0
info:
  title: Zoho People Plus Sync Service API
  version: 1.0.0
paths:
  /sync:
    post:
      summary: Trigger manual sync of Zoho employee data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                sync_interval:
                  type: integer
      responses:
        '200':
          description: Sync started
        '400':
          description: Invalid request
  /candidates:
    get:
      summary: Retrieve generated candidate details
      responses:
        '200':
          description: List of candidate details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CandidateDetails'
components:
  schemas:
    CandidateDetails:
      type: object
      properties:
        candidate_id:
          type: string
        employee_id:
          type: string
        profile:
          type: string
        skills:
          type: array
          items:
            type: string
        experience:
          type: string
        summary:
          type: string
        generated_at:
          type: string
          format: date-time
