# OpenAPI Contract: Candidate Location and Experience

openapi: 3.0.0
info:
  title: Candidate API
  version: 1.0.0
paths:
  /candidates:
    get:
      summary: Get all candidates
      responses:
        '200':
          description: List of candidates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candidate'
    post:
      summary: Create a new candidate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
      responses:
        '201':
          description: Candidate created
  /candidates/{id}:
    get:
      summary: Get candidate by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Candidate details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
    patch:
      summary: Update candidate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
      responses:
        '200':
          description: Candidate updated
components:
  schemas:
    Candidate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
          description: Free text, e.g., "Bangalore, India"
        experience:
          type: number
          format: float
          description: Years of experience
        experience_description:
          type: string
          description: Optional text description
        skills:
          type: array
          items:
            type: string
      required:
        - id
        - name
